### ISSUE TITLE
No Blobs returned from Blob.Enumerate() while using DiskStorage

### ISSUE THREAD

**Issue by teh-random-name** [jchristn/BlobHelper#1]
**Operating system and version**: `Windows 10 / .NET Core 3.1.17`
**Library Version**: (NuGet) 2.1.3
**Issue encountered**: Different Enumeration results (Disk vs S3)
**Expected behavior**: Listing of objects
**Steps to reproduce**: Call `Blob.Enumerate()` while using DiskStorage

**Sample code encapsulating the problem**:

```csharp
DiskSettings diskSettings = new DiskSettings("storage");
var BlobClient = new Blobs(diskSettings);
var blobs = await BlobClient.Enumerate();

foreach (var blobMeta in blobs.Blobs)
    Console.WriteLine(blobMeta.Key);
```

**Exception details**: N/A

I noticed while using DiskStorage that enumerating over the files returns odd results compared to S3.
For example, when enumerating over a S3 bucket, I get back blobs with keys using the full path without having to provide a prefix.

When I switch to DiskStorage, if I enumerate, I only get back directories, not files.
This is the same regardless if I provide a prefix or not.

I believe the issue is related to the flags passed to `Directory.EnumerateFiles`.
I also believe the call to `Directory.EnumerateDirectories` is unneeded as `Directory.EnumerateFiles` would provide the same information.

In my own testing, using `SearchOption.AllDirectories` instead returns what I'd expect when enumerating.

I'm opening this as an issue incase I'm misunderstanding the purpose of DiskStorage.

Ref:
https://github.com/jchristn/BlobHelper/blob/9953f09ab6455bf5086f1d5dad8c98cf292d29c5/BlobHelper/Blobs.cs#L1085
https://github.com/jchristn/BlobHelper/blob/9953f09ab6455bf5086f1d5dad8c98cf292d29c5/BlobHelper/Blobs.cs#L1089

**Comment by teh-random-name** [comment]
I discovered this issue while writing a small ASPNET Web API, I'm dynamically generating the directory so I can't reliably prefix the folder with `./`.

That being said, I tested it with a statically set directory.
I'm still not getting any blobs.

Output of dir on the folder in question:
```
    Directory: D:\Projects\S3Testing\S3Testing\bin\Debug\netcoreapp3.1\backend-storage


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----         10/6/2021   8:02 PM                Comic 1
d-----         10/6/2021   8:02 PM                Comic 10
d-----         10/6/2021   8:02 PM                Comic 11
d-----         10/6/2021   8:02 PM                Comic 12
d-----         10/6/2021   8:02 PM                Comic 13
d-----         10/6/2021   8:02 PM                Comic 14
d-----         10/6/2021   8:02 PM                Comic 15
d-----         10/6/2021   8:02 PM                Comic 16
d-----         10/6/2021   8:02 PM                Comic 17
```

Output from the test program with my content copied to the output folder.
![image](https://user-images.githubusercontent.com/3823744/136300287-9a3e5557-435f-4c1a-9c1c-b4d9715ef616.png)

**Comment by jchristn** [comment]
Can you try with an explicit path in your code (D:/foo/bar/) instead of a relative path (./ etc)?  I suspect some foul play from the environment.

**Comment by jchristn** [comment]
I assume this is more like what you are expecting?  (from the ```Test``` project)  By the way, I completely agree with you, and am thankful that you found this issue.  I hadn't even considered prefixes/folders!

I made a new version (2.1.4) and gave you credit in the README/commit.  Please let me know if this works the way you expect!

Cheers,
Joel

NuGet: https://www.nuget.org/packages/BlobHelper/2.1.4
Commit: https://github.com/jchristn/BlobHelper/commit/f4dd0544e68e27c19a0406d9abc8a867dfeb65e7

**Comment by teh-random-name** [comment]
I'll give it a test this weekend, thanks!

**Comment by teh-random-name** [comment]
Yup all looks correct!
Thanks again for updating it.

There are some other things I'd like to have in the library when dealing with local files but that will be for another day.

**Comment by jchristn** [comment]
Awesome!  I'd love any suggestions or pull requests :) glad it is to your liking
