### ISSUE TITLE
Update to Azure.Storage.Blobs

### ISSUE THREAD

**Issue by mbarmettler** [jchristn/BlobHelper#12]
Would have been nice, to see such a helper for the New Azure.Storage.Blobs Package.
Seems like this Repo uses the old "Microsoft.WindowsAzure.Storage;" package - which is depricated and completly different to handle then the new one.

**Comment by jchristn** [comment]
I'd be happy to take a PR on this.  Moving this to a discussion because it isn't a functionality issue within the library.

**Comment by jchristn** [comment]
By the way, I started on a prototype to migrate to ```Azure.Storage.Blobs```, and everything is working except enumeration.  I'm looking for a consistent means of enumerating (to ensure consistency with other implementations such as S3), and have a question up on SO here: https://stackoverflow.com/questions/75010180/enumerating-large-azure-blob-containers-using-azure-storage-blobs

**Comment by jchristn** [comment]
Hi @mbarmettler just a heads up, thanks to your recommendation, I migrated to the newer ```Azure.Storage.Blobs```.  Please re-open if any issues.

NuGet: https://www.nuget.org/packages/BlobHelper/4.0.1
Commit: https://github.com/jchristn/BlobHelper/commit/a90aff837a2e96141697eaab379d917859b440c7
