### ISSUE TITLE
DiskEnumerate() will never return continuation token

### ISSUE THREAD

**Issue by johangranath** [jchristn/BlobHelper#14]
Hi,
Trying to get continuation token back from `DiskEnumerate()`
Looking at the call of `DiskBuildContinuationToken(int start, int count)`

The call is made with these parameters:
`ret.NextContinuationToken = DiskBuildContinuationToken(startIndex + count, count);`

First line in `DiskBuildContinuationToken()`
`if (start >= count) return null;`

So looks like only negative values on `startIndex ` on any `count ` can ever return a result that is not null?

**Comment by jchristn** [comment]
Hi @johangranath thanks for pointing this out, I will take a look.

**Comment by jchristn** [comment]
Thank you so much @johangranath - I integrated a fix in v4.0.4.  Please re-open if any issues!  Thanks again!

NuGet: https://www.nuget.org/packages/BlobHelper/4.0.4
Commit: https://github.com/jchristn/BlobHelper/commit/3e583f10e2f4119449e52be68da682420816065a
