### ISSUE TITLE
Add function to create folders

### ISSUE THREAD

**Issue by hade94** [jchristn/BlobHelper#7]
Hi,

first of all, thanks for creating this library.

I didnt find a way of creating empty folders. Is there a possibility of adding this in a future release?

Thanks,

**Comment by jchristn** [comment]
Hi @hade94 you should be able to do this by supplying a ```new byte[0]``` as the data, or, ```String.Empty``` to the ```Write``` API.  Just make sure the object name ends in ```/```.  Did you try this?  

BTW - thank you for your kind words!

**Comment by hade94** [comment]
Hi @jchristn,

it works like charm by setting the mimetype to "folder/folder".

Thanks for the quick reponse.
